# Generated by Django 5.2.1 on 2025-05-20 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='BlogCategory',
        ),
        migrations.RenameModel(
            old_name='Location',
            new_name='GeographicLocation',
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='PublishedPost',
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Текст')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('comment_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
                ('related_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.publishedpost', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
