# Generated by Django 5.2.1 on 2025-05-20 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_category_blogcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='related_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.publishedpost', verbose_name='Пост'),
        ),
    ]
